[package]
name = "oefs"
version = "0.0.0"
description = "My playground for learning Rust"
license = "Apache-2.0"
edition = "2024"

[[bin]]
name = "oefs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
